name: chinese-roberta-wwm-ext-large
dir: "modules/text/semantic_model/chinese-roberta-wwm-ext-large"
exclude:
  - README.md
  - test_context.py
  - test_embedding.py
resources:
  -
    url: https://paddlehub.bj.bcebos.com/model/nlp/chinese-roberta-wwm-ext-large/assets.tar.gz
    dest: assets
    uncompress: True
