name: chinese-bert-wwm-ext
dir: "modules/text/semantic_model/chinese-bert-wwm-ext"
exclude:
  - README.md
  - test_context.py
  - test_embedding.py
resources:
  -
    url: https://paddlehub.bj.bcebos.com/model/nlp/chinese-bert-wwm-ext/assets.tar.gz
    dest: assets
    uncompress: True
