name: ernie
dir: "modules/text/lexical_analysis/ernie"
exclude:
  - README.md
  - test_context.py
  - test_embedding.py
resources:
  -
    url: https://paddlehub.bj.bcebos.com/model/nlp/ernie/assets.tar.gz
    dest: assets
    uncompress: True
