name: roberta_wwm_ext_chinese_L_24_H_1024_A_16_distillation
dir: "modules/text/semantic_model/roberta_wwm_ext_chinese_L_24_H_1024_A_16_distillation"
exclude:
  - README.md
  - test_context.py
  - test_embedding.py
resources:
  -
    url: https://paddlehub.bj.bcebos.com/model/nlp/roberta_wwm_ext_chinese_L_24_H_1024_A_16_distillation/assets.tar.gz
    dest: assets
    uncompress: True
