name: roberta_wwm_ext_chinese_L_3_H_768_A_12
dir: "modules/text/semantic_model/roberta_wwm_ext_chinese_L_3_H_768_A_12"
exclude:
  - README.md
  - test_context.py
  - test_embedding.py
resources:
  -
    url: https://paddlehub.bj.bcebos.com/model/nlp/roberta_wwm_ext_chinese_L_3_H_768_A_12/assets.tar.gz
    dest: assets
    uncompress: True
